#goal definition
geometry_msgs/PointStamped point_stamped
uint8 command
#Constants for command value
uint8 UNKNOWN=0
uint8 MOVE_STANDARD_POSE=1
uint8 MOVE_RIGHT_ARM=2
uint8 MOVE_LEFT_ARM=3
uint8 MOVE_RIGHT_GRIPPER=4
uint8 MOVE_LEFT_GRIPPER=5
---
#result definition
bool successful
uint8 status
#Constants for status value
uint8 SUCCESS=0
uint8 OUT_OF_RANGE=1
uint8 COLLISION=2
uint8 UNMANAGEBLE_ERROR=3
---
#feedback definition
#bool finished
